import { writeFile } from 'fs/promises'
import type { ConfigKey } from '../types.js'

interface NestedShape {
  [key: string]: NestedShape | null
}

function buildNestedShape(keys: ConfigKey[]): NestedShape {
  const root: NestedShape = {}
  for (const { key } of keys) {
    const parts = key.split('.')
    let cur = root
    for (let i = 0; i < parts.length; i++) {
      const p = parts[i]
      if (i === parts.length - 1) {
        cur[p] = null
      } else {
        cur[p] = (cur[p] as NestedShape) ?? {}
        cur = cur[p] as NestedShape
      }
    }
  }
  return root
}

function shapeToTs(shape: NestedShape, indent = 2): string {
  const pad = ' '.repeat(indent)
  const lines: string[] = ['{']
  for (const [k, v] of Object.entries(shape)) {
    if (v === null) {
      lines.push(`${pad}${k}: string`)
    } else {
      lines.push(`${pad}${k}: ${shapeToTs(v, indent + 2)}`)
    }
  }
  lines.push(' '.repeat(indent - 2) + '}')
  return lines.join('\n')
}

export function generateTypes(keys: ConfigKey[], interfaceName = 'AppConfig'): string {
  const shape = buildNestedShape(keys)
  return `export interface ${interfaceName} ${shapeToTs(shape)}\n`
}

export async function writeTypes(keys: ConfigKey[], outPath: string, interfaceName = 'AppConfig'): Promise<void> {
  const content = `// Auto-generated by config-sentinel. Do not edit.\n\n${generateTypes(keys, interfaceName)}`
  await writeFile(outPath, content, 'utf-8')
}
